### ISSUE TITLE
No response with script

### ISSUE THREAD

**Issue by 0000vt** [reyemb/AISExplorer#3] opened 2023-12-19 09:23 UTC
With an easy debug script, nothing happens. It just hangs and waits and no response is retrieved.

`from aisexplorer.AIS import AIS

print(AIS().get_location(255805840))`

After a while:

aisexplorer.Exceptions.NoResultsError: After 10 attempts still no results are given. If you think this is an error in the module raise an issue at https://github.com/reyemb/AISExplorer

**Comment by reyemb** [comment] 2023-12-19 11:14
Which Version are you currently using?

**Comment by 0000vt** [comment] 2023-12-19 12:24
0.2.1 from pypi

**Comment by reyemb** [comment] 2023-12-19 20:01
I have just uploaded version 0.2.2 to pypi can you please use this version and check if the problem still exists?

**Comment by 0000vt** [comment] 2023-12-20 07:48
Yes thank you. So only the old vessel image and chrome version were blocking the request?

**Comment by reyemb** [comment] 2024-03-10 17:15
Apologies for the delayed response due to catching up with a backlog of work. It appears the root cause of the Cloudflare issue was the newly added functionalities for logged-in users. This combination was mistakenly identified as malicious by Cloudflare. I am committed to being more active and responsive in the future.

Maybe it was also in combination with the anonymous proxies. I can´t remember :)

**Comment by reyemb** [comment] 2024-03-10 17:15
Will be closed. Since it is solved and can be reopened if it happens again

**Closed as completed by reyemb** 2024-03-10 17:15 UTC
